      DOUBLE PRECISION FUNCTION GDAEFN(X)
C
C   THIS IS THE FUNCTION INTEGRATED TO FIND GAUSSIAN GDAE RESPONSE
C   (SEE NELEM = 14.  HERE 1400)    
      IMPLICIT REAL*8(A-H,O-Z)
      REAL*8 X
      COMMON /CM9/TOMEGA,XIGDAE,ICHG,IWT
      COMMON /CM12/ CELCAP,ATEMP,WF,MAXFEV,ICF,MDE,JCDX
C
      XCU = X*ICHG - (X/XIGDAE)**2
      IF(DABS(XCU).GT.3.D2) XCU = DSIGN(3.D2,XCU)
      XEE = DEXP(X)
      IF(IWT.EQ.1) THEN
        GDAEFN = DEXP(XCU)/(1.D0 + (TOMEGA*XEE)**2)
C
        IF(MDE.LT.0) GDAEFN = GDAEFN*XEE
      ELSE 
        XAR = XCU - TOMEGA*DEXP(-X)
        IF(XAR.LT.-5.D1) THEN
          GDAEFN = 0
        ELSE
          GDAEFN = DEXP(XAR)
        ENDIF
      ENDIF 
      RETURN
      END
