      DOUBLE PRECISION FUNCTION GDAETN(X)
C
C   THIS IS THE FUNCTION INTEGRATED TO FIND THE GDAE TRAN RESPONSE
C
      IMPLICIT REAL*8(A-H,O-Z)
      REAL*8 X
      COMMON /CM79/ TT,PSI,GAM,DELI
C
      XP = PSI*X
      XG = (DELI*X)**2
      XA = -GAM*X
      IF(DABS(XA).GT.1.D2) XA = DSIGN(1.D2,XA)
      XGE = DEXP(XA)
      XSS = XP -XG -TT*XGE
      IF(DABS(XSS).GT.1.D2) XSS = DSIGN(1.D2,XSS)
      GDAETN = DEXP(XSS)
      RETURN
      END
