      DOUBLE PRECISION FUNCTION WW5(X)
C
C   THIS IS THE FUNCTION INTEGRATED TO FIND KWW WITH BETA=.5.  3200
C
      IMPLICIT REAL*8(A-H,O-Z)
      REAL*8 X
      COMMON /CM5/ TOMEGA,PHICOM,IV
      COMMON /CM12/ CELCAP,ATEMP,WF,MAXFEV,ICF,MDE,JCDX
C
C   HERE X IS LN(TAU)
C
      EYS = DEXP(X)
      E4Y = DEXP(-EYS/4.D0)
       EY = DEXP(IV*X/2.D0)
C
C   ************   CALCULATE DRT   **********************
C   FIRST, DSD OR CSDO
      DRT = EY*E4Y
C   HERE CSD1
      IF(MDE.LT.0) DRT = DRT*EYS
C   
C   TRANSIENT RESPONSE
      IF(ABS(MDE).EQ.8) THEN
        TOMEGI = TOMEGA/EYS         
        WW5 = DRT*DEXP(-TOMEGI)
C
C   FREQUENCY RESPONSE
      ELSE
        WW5 = DRT/(1.D0 + (TOMEGA*EYS)**2)
      ENDIF       
C
      RETURN
      END
