C
C       MODIFIED FOR LEVMpy JEREMY SMITH 3/31/2017
C
      FUNCTION CDCOTH(X)
C         ACTUALLY X * COTH(X)
      COMPLEX*16 CDTEMP,X,CDCOTH,CDI
      DOUBLE PRECISION DABS, DSIGN, ZR
      ZR = DREAL(X)
      IF (DABS(ZR) .GT. 1.3D2) GOTO 100
      IF (CDABS(X) .GT. 7.D-3) GOTO 10
      CDCOTH = 1.D0 + X*X/3.D0 - X**4/45.D0
      RETURN
   10 CONTINUE
      CDTEMP = CDEXP(X)
      CDI = 1.D0/CDTEMP
      CDCOTH = X*(CDTEMP + CDI)/(CDTEMP - CDI)
      RETURN
  100 CDCOTH = X*DCMPLX(DSIGN(1.D0,ZR),0.D0)
      RETURN
      END
