C
C   ADDED PART OF LEVM CNLS PROGRAM: FOR REGULARIZATION
C
C       J.R. Macdonald, 10/20/96
C
C       MODIFIED FOR LEVMpy JEREMY SMITH 3/31/2017
C
      SUBROUTINE FCN1(MPN,NFREI,X,FVEC,FJAC,LDFJAC,IFLAG)
      IMPLICIT REAL*8 (A-H,O-Z)
      INTEGER MPN,NFREI,LDFJAC,IFLAG
      REAL*8 X,FVEC,FJAC
      EXTERNAL FCN,REGMAX
      CHARACTER*1 DATTYP,FUN,DFIT,PFIT
      INCLUDE 'SIZE.INC'
      DIMENSION X(40),FVEC(MPN),FJAC(MPN,NFREI),XL(40),XR(40)
      COMMON /CM2/ Y(NPT2),R(NPT2),FJ(NPT2),P(NTOT),DRSS,ROE,RKE,
     + NS(NPAFR),NFREE(NTOT),N,ICNT,MN,IRCH,IXI,DATTYP
      COMMON /CM3/ CELCAP,FUN,DFIT,PFIT
      COMMON /CM16/ IOP,IORIG,NYC,J,IPRINT,LDFJYC,MODE,IFP,IRE,ISTP,JFP,
     + NPH,INE
C
C   MK IS KY HERE (TWICE # OF FREQS); MD IS ORIG. NO. OF FREQS.
C       MPN IS MK + NFREI
C              ICNT = ICNT + 1
C
C   WHEN P33=0, MPN AND LDFJAC INPUTS ARE ORIG MK=KY VALUES
C   OTHERWISE, MPN = KY + NFREI = LDFJAC
C
      IF(P(33).EQ.0.D0) THEN
        MK = MPN
        IF(DATTYP.EQ.'I') THEN
            LDFJAC = 2*MK
        ELSE
            LDFJAC = MK
        ENDIF
      ELSE
        MK = MPN - NFREI
      ENDIF
C
      CALL FCN(MK,NFREI,X,FVEC,FJAC,LDFJAC,IFLAG)
C
C     NO REGULARIZATION IF P(33) = 0
C
      IF(P(33).EQ.0.D0) GOTO 90
C
C     Cm REGULATED AND TAUm NOT REGULATED (USES P33) 0DD.  TAUS FIXED    
C
      P33A = DABS(P(33))
      IF(P(33).LT.0.D0) THEN
        ING = 1
        DO JJ = 1,NFREI
          XL(JJ) = DLOG(DABS(X(JJ)))
        ENDDO
      ELSE
        ING = 0
        DO JJ = 1,NFREI
          XL(JJ) = X(JJ)
        ENDDO
      ENDIF
C
      NEND = NFREI - INE
      DO KK = 1,NEND
        IF(KK.LE.14) THEN
          XR(KK) = XL(KK)
        ELSE
          XR(KK) = XL(KK + INE)
        ENDIF
      ENDDO
C   
      IP39 = INT(DABS(P(39)) + 0.01D0)
C
      CALL REGMAX(NEND,IP39,ING,IFLAG,NFREI,MPN,MK,XR,FVEC,
     + FJAC,P33A)
C
C     CALCULATE PARTS OF OBJECTIVE FUNCTION
C
90    CONTINUE
      RETURN
      END
